Added GIF image I/O plugin.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1436,13 +1436,93 @@ fi
 
 
 
+gif_val=no
+ac_safe=`echo "gif_lib.h" | sed 'y%./+-%__p_%'`
+echo $ac_n "checking for gif_lib.h""... $ac_c" 1>&6
+echo "configure:1443: checking for gif_lib.h" >&5
+if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  cat > conftest.$ac_ext <<EOF
+#line 1448 "configure"
+#include "confdefs.h"
+#include <gif_lib.h>
+EOF
+ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
+{ (eval echo configure:1453: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
+if test -z "$ac_err"; then
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=yes"
+else
+  echo "$ac_err" >&5
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=no"
+fi
+rm -f conftest*
+fi
+if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+  echo $ac_n "checking for main in -lungif""... $ac_c" 1>&6
+echo "configure:1470: checking for main in -lungif" >&5
+ac_lib_var=`echo ungif'_'main | sed 'y%./+-%__p_%'`
+if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  ac_save_LIBS="$LIBS"
+LIBS="-lungif  $LIBS"
+cat > conftest.$ac_ext <<EOF
+#line 1478 "configure"
+#include "confdefs.h"
+
+int main() {
+main()
+; return 0; }
+EOF
+if { (eval echo configure:1485: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=yes"
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=no"
+fi
+rm -f conftest*
+LIBS="$ac_save_LIBS"
+
+fi
+if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+  gif_val=yes
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+if test $gif_val = "yes"; then
+	GIF_FILTER="gif"
+	PLUGIN_GIF="gif_io.plg"
+else
+	GIF_FILTER=""
+	PLUGIN_GIF=""
+	echo "configure: warning: UNGIF library not available so gif filter not compiled" 1>&2
+fi
+
+
+
 echo $ac_n "checking for working const""... $ac_c" 1>&6
-echo "configure:1441: checking for working const" >&5
+echo "configure:1521: checking for working const" >&5
 if eval "test \"`echo '$''{'ac_cv_c_const'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1446 "configure"
+#line 1526 "configure"
 #include "confdefs.h"
 
 int main() {
@@ -1491,7 +1571,7 @@ ccp = (char const *const *) p;
 
 ; return 0; }
 EOF
-if { (eval echo configure:1495: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:1575: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   ac_cv_c_const=yes
 else
@@ -1512,14 +1592,14 @@ EOF
 fi
 
 echo $ac_n "checking whether byte ordering is bigendian""... $ac_c" 1>&6
-echo "configure:1516: checking whether byte ordering is bigendian" >&5
+echo "configure:1596: checking whether byte ordering is bigendian" >&5
 if eval "test \"`echo '$''{'ac_cv_c_bigendian'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   ac_cv_c_bigendian=unknown
 # See if sys/param.h defines the BYTE_ORDER macro.
 cat > conftest.$ac_ext <<EOF
-#line 1523 "configure"
+#line 1603 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <sys/param.h>
@@ -1530,11 +1610,11 @@ int main() {
 #endif
 ; return 0; }
 EOF
-if { (eval echo configure:1534: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:1614: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   # It does; now see whether it defined to BIG_ENDIAN or not.
 cat > conftest.$ac_ext <<EOF
-#line 1538 "configure"
+#line 1618 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <sys/param.h>
@@ -1545,7 +1625,7 @@ int main() {
 #endif
 ; return 0; }
 EOF
-if { (eval echo configure:1549: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:1629: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   ac_cv_c_bigendian=yes
 else
@@ -1565,7 +1645,7 @@ if test "$cross_compiling" = yes; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
-#line 1569 "configure"
+#line 1649 "configure"
 #include "confdefs.h"
 main () {
   /* Are we little or big endian?  From Harbison&Steele.  */
@@ -1578,7 +1658,7 @@ main () {
   exit (u.c[sizeof (long) - 1] == 1);
 }
 EOF
-if { (eval echo configure:1582: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1662: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   ac_cv_c_bigendian=no
 else
@@ -1602,12 +1682,12 @@ EOF
 fi
 
 echo $ac_n "checking for size_t""... $ac_c" 1>&6
-echo "configure:1606: checking for size_t" >&5
+echo "configure:1686: checking for size_t" >&5
 if eval "test \"`echo '$''{'ac_cv_type_size_t'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1611 "configure"
+#line 1691 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #if STDC_HEADERS
@@ -1636,7 +1716,7 @@ fi
 
 
 echo $ac_n "checking whether to link statically or not""... $ac_c" 1>&6
-echo "configure:1640: checking whether to link statically or not" >&5
+echo "configure:1720: checking whether to link statically or not" >&5
 # Check whether --enable-static-link or --disable-static-link was given.
 if test "${enable_static_link+set}" = set; then
   enableval="$enable_static_link"
@@ -1655,7 +1735,7 @@ fi
 echo "$ac_t""$STATIC_VAL" 1>&6
 
 echo $ac_n "checking whether to add profiling information or not""... $ac_c" 1>&6
-echo "configure:1659: checking whether to add profiling information or not" >&5
+echo "configure:1739: checking whether to add profiling information or not" >&5
 # Check whether --enable-profile or --disable-profile was given.
 if test "${enable_profile+set}" = set; then
   enableval="$enable_profile"
@@ -1674,7 +1754,7 @@ fi
 echo "$ac_t""$PROFILE_VAL" 1>&6
 
 echo $ac_n "checking whether to enable debug info or not""... $ac_c" 1>&6
-echo "configure:1678: checking whether to enable debug info or not" >&5
+echo "configure:1758: checking whether to enable debug info or not" >&5
 # Check whether --enable-debug or --disable-debug was given.
 if test "${enable_debug+set}" = set; then
   enableval="$enable_debug"
@@ -1693,7 +1773,7 @@ fi
 echo "$ac_t""$DEBUG_VAL" 1>&6
 
 echo $ac_n "checking whether to enable experimental code or not""... $ac_c" 1>&6
-echo "configure:1697: checking whether to enable experimental code or not" >&5
+echo "configure:1777: checking whether to enable experimental code or not" >&5
 # Check whether --enable-experimental or --disable-experimental was given.
 if test "${enable_experimental+set}" = set; then
   enableval="$enable_experimental"
@@ -1878,6 +1958,7 @@ trap 'rm -fr `echo "\
         plugins/image_filter/fog/Makefile:Makefile.plugin.in \
         plugins/image_filter/text/Makefile:Makefile.plugin.in \
         plugins/image_io/Makefile \
+        plugins/image_io/gif/Makefile:Makefile.plugin.in \
         plugins/image_io/jpeg/Makefile:Makefile.plugin.in \
         plugins/image_io/png/Makefile:Makefile.plugin.in \
         plugins/image_io/tga/Makefile:Makefile.plugin.in \
@@ -1971,6 +2052,8 @@ s%@JPEG_FILTER@%$JPEG_FILTER%g
 s%@PLUGIN_JPEG@%$PLUGIN_JPEG%g
 s%@PNG_FILTER@%$PNG_FILTER%g
 s%@PLUGIN_PNG@%$PLUGIN_PNG%g
+s%@GIF_FILTER@%$GIF_FILTER%g
+s%@PLUGIN_GIF@%$PLUGIN_GIF%g
 s%@STATIC_LINK@%$STATIC_LINK%g
 s%@PROFILE@%$PROFILE%g
 s%@DEBUG_INFO@%$DEBUG_INFO%g
@@ -2049,6 +2132,7 @@ CONFIG_FILES=\${CONFIG_FILES-"\
         plugins/image_filter/fog/Makefile:Makefile.plugin.in \
         plugins/image_filter/text/Makefile:Makefile.plugin.in \
         plugins/image_io/Makefile \
+        plugins/image_io/gif/Makefile:Makefile.plugin.in \
         plugins/image_io/jpeg/Makefile:Makefile.plugin.in \
         plugins/image_io/png/Makefile:Makefile.plugin.in \
         plugins/image_io/tga/Makefile:Makefile.plugin.in \
